### ISSUE TITLE
New User Experience

### ISSUE THREAD

**Issue by thornyd** [instinct/GameFroot#293] opened 2012-02-16 03:59 UTC
here's the pic:
http://i42.tinypic.com/fz3tw5.jpg

**Comment by InstinctBrett** [comment] 2012-03-02 01:47
This is not a helpful issue. closing so you'll hopefully re-write it into a more helpful 'what the problem is and what needs to be done'.

**Closed as completed by InstinctBrett** 2012-03-02 01:47 UTC

**Comment by thornyd** [comment] 2012-03-02 02:43
Hey Brett, Dan told me to write that - I know as much about it as you
do. Probably best to ask him.

On 2 March 2012 14:47, Brett Taylor
reply@reply.github.com
wrote:
